# Generated by Django 4.2.14 on 2024-10-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio_files/')),
                ('prediction', models.CharField(max_length=50)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
