# Generated by Django 4.2.14 on 2024-10-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0002_videoprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=200)),
            ],
        ),
    ]
