# Generated by Django 4.2.16 on 2024-12-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0003_chatbot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='uploads/')),
                ('image2', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
