# Generated by Django 4.2.16 on 2025-02-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0004_imageupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chatbot',
        ),
        migrations.DeleteModel(
            name='ImageUpload',
        ),
        migrations.AlterField(
            model_name='audioprediction',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='videoprediction',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
