# Generated by Django 4.2.16 on 2025-02-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0005_delete_chatbot_delete_imageupload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('label', models.CharField(default='data', max_length=20)),
            ],
        ),
    ]
